' Localization tables for the FileDO GUI.
' Each language returns "key|value" lines; GetDict splits them into a dictionary.
' Keep "|" out of values. Use plain "-" (not em-dash) and ".." (not "...").
' A literal \n inside a value is a line break: MainForm.LText expands it for the multi-line
' dialog texts. Everything else is single-line and used as it stands.
Module Localization

    Public ReadOnly Languages As String() = {"en", "ru", "uk", "de", "fr"}
    Public ReadOnly LanguageNames As String() = {"English", "Русский", "Українська", "Deutsch", "Français"}

    ' Expands the \n line-break marker the tables use, because every value has to stay on one
    ' line inside a "key|value" entry.
    Public Function Multiline(value As String) As String
        If value Is Nothing Then Return ""
        Return value.Replace("\n", Environment.NewLine)
    End Function

    Public Function GetDict(lang As String) As Dictionary(Of String, String)
        Dim src As String()
        Select Case lang
            Case "ru" : src = RuLines()
            Case "uk" : src = UkLines()
            Case "de" : src = DeLines()
            Case "fr" : src = FrLines()
            Case Else : src = EnLines()
        End Select
        Dim d As New Dictionary(Of String, String)
        ' English is the fallback for any key a translation forgot.
        If lang <> "en" Then
            For Each ln As String In EnLines()
                Dim j As Integer = ln.IndexOf("|"c)
                If j > 0 Then d(ln.Substring(0, j)) = ln.Substring(j + 1)
            Next
        End If
        For Each ln As String In src
            Dim i As Integer = ln.IndexOf("|"c)
            If i > 0 Then d(ln.Substring(0, i)) = ln.Substring(i + 1)
        Next
        Return d
    End Function

    Private Function EnLines() As String()
        Return New String() {
            "ui_title|FileDO - command builder",
            "ui_lang|Language:",
            "ui_target|Target:",
            "ui_operation|Operation:",
            "ui_drive|Drive:",
            "ui_path|Path:",
            "ui_source|Source:",
            "ui_list|List file:",
            "ui_folder|Folder:",
            "ui_dest|Destination:",
            "ui_size|Size (MB):",
            "ui_flags|Flags:",
            "ui_browse|Browse",
            "ui_copy|Copy command",
            "ui_run|RUN",
            "ui_about|About",
            "ui_close|Close",
            "ui_send_logs|Send logs to the author",
            "about_tip|Version, links, and sending the logs to the author",
            "about_title|About FileDO",
            "about_tagline|Storage speed tests, fake-capacity detection, secure wipe, fill and duplicate management for Windows - a command-line tool and this command builder for it.",
            "about_build|GUI build:",
            "about_cli|CLI filedo.exe:",
            "about_author|Author:",
            "about_links|Links:",
            "about_site|Website and downloads",
            "about_source|Source code on GitHub",
            "about_issues|Report an issue",
            "about_privacy|Privacy: no telemetry",
            "about_portfolio|Other tools by the author",
            "about_license|MIT License. Free to use, and the full source is open.",
            "about_logs_hint|Something behaving wrongly? Send the logs and it can be looked at. The logs are collected into one zip that you see first, and you send the mail yourself.",
            "logs_title|FileDO - send logs to the author",
            "logs_tip|Pack the FileDO log files found on this machine into one zip, then open your mail program addressed to the author. Nothing is sent until you send the mail yourself.",
            "logs_confirm|FileDO will collect the log and report files it wrote on this machine into one zip.\n\nWhat goes in: the GUI debug log, the operation history, the check, compare and delete reports, the skip list, and a short report about this build and this Windows.\n\nFile paths inside those logs can contain your own folder and account names. The zip stays on your disk, so you can open it and remove anything you do not want to share.\n\nNothing is sent automatically: your mail program opens with the author address, and you attach the file and press Send.\n\nBuild the zip now?",
            "logs_none|No FileDO log files were found on this machine, so there is nothing to send yet.\n\nTo produce a log, start the GUI as: filedo_win.exe -debug\nOr run a command that writes a report - check, compare, or a delete rule.",
            "logs_ready|The zip is ready:\n{0}\n\nFiles collected: {1}. The folder is open with the file selected, and the full path is on the clipboard.\n\nLast step: attach that file to the mail that just opened, and press Send.",
            "logs_partial|Some steps did not work:",
            "logs_error|Could not build the log archive:\n{0}",
            "hl_example|Example:",
            "hl_note|Note:",
            "hl_flags|Active flags:",
            "dup_title|Duplicate options",
            "dup_old|Keep newest (old)",
            "dup_new|Keep oldest (new)",
            "dup_abc|Keep last alpha (abc)",
            "dup_xyz|Keep first alpha (xyz)",
            "dup_move|Move duplicates to:",
            "cmp_label|Delete rule:",
            "hl_rule|Rule:",
            "cmprule_none|Report differences only; delete nothing.",
            "cmprule_source|Delete files in Source that also exist in Target.",
            "cmprule_target|Delete files in Target that also exist in Source.",
            "cmprule_old|Delete the older file of each matched pair (equal time: skip).",
            "cmprule_new|Delete the newer file of each matched pair (equal time: skip).",
            "cmprule_small|Delete the smaller file of each matched pair (equal size: skip).",
            "cmprule_big|Delete the bigger file of each matched pair (equal size: skip).",
            "cmprule_old_target|Delete the older file of each pair, but only when that side is Target.",
            "cmprule_new_source|Delete the newer file of each pair, but only when that side is Source.",
            "cmprule_small_source|Delete the smaller file of each pair, but only when that side is Source.",
            "cmprule_big_target|Delete the bigger file of each pair, but only when that side is Target.",
            "cdrule_old|Keep the newest copy; delete or move the older duplicates.",
            "cdrule_new|Keep the oldest copy; delete or move the newer duplicates.",
            "cdrule_abc|Keep the last name alphabetically; remove the other duplicates.",
            "cdrule_xyz|Keep the first name alphabetically; remove the other duplicates.",
            "op_info|Show target details (size, free space, file system). Read-only, changes nothing.",
            "op_speed|Measure real read/write speed with a temporary file, then delete it.",
            "op_test|Detect fake capacity: writes ~100 verification files (~1% each), checks them, reports if the device is genuine. 'del' auto-cleans.",
            "op_fill|Fill free space with test files until full. Add 'del' to wipe them after - secure-erases free space.",
            "op_clean|Delete FileDO test files (FILL_*, speedtest_*) left on the target.",
            "op_cd|Find duplicate files by MD5 and apply the chosen rule (keep oldest/newest/alphabetical; delete or move).",
            "op_copy|Copy source to destination with auto-tuned strategy, progress and timeout protection.",
            "op_fastcopy|High-speed parallel copy for large datasets.",
            "op_synccopy|Single-threaded synchronized copy (less caching) - for measuring real I/O.",
            "op_balanced|Balanced copy tuned for HDD-to-HDD (4 threads, 64 MB buffers).",
            "op_maxcopy|Maximum-performance copy (16 threads, 128 MB buffers).",
            "op_smartcopy|Analyze the drives and pick the best copy strategy automatically.",
            "op_safecopy|Ultra-safe copy for damaged drives: skips unreadable files and logs them.",
            "op_wipe|Delete the folder's contents fast (delete & recreate). Asks to type WIPE first.",
            "op_compare|Compare two folder trees and report differences; an optional rule deletes matched files.",
            "op_check|Read every file to find unreadable or slow ones; flags damaged files.",
            "op_probe|Fast raw-I/O capacity probe. Requires Administrator, ~1 min.",
            "op_recover|Recover a drive after a probe (chkdsk + optional quick format).",
            "op_from|Run a batch of filedo commands from a list file (one per line).",
            "op_hist|Show the recent operation history.",
            "op_help|Show the full command-line help.",
            "fl_max|max: use the maximum size (10 GB for speed; fill to capacity).",
            "fl_del|del: delete the test files automatically after the run.",
            "fl_nodel|nodel: keep the test file instead of deleting it.",
            "fl_short|short: brief output only.",
            "fl_hist|hist: log this run to history.json.",
            "fl_force|--force: skip the WIPE confirmation (normal targets only).",
            "ex_device|Example: pick a drive - C:  D:  E:",
            "ex_folder|Example: C:\Temp   D:\Data",
            "ex_network|Example: \\server\share",
            "ex_file|Example: C:\data\archive.zip",
            "note_sysdrive|C: is the system drive. Write tests (test/fill/speed) are redirected to %TEMP%\FileDO_Operations (fallback C:\TEMP) and ask to confirm - this protects Windows."
        }
    End Function

    Private Function RuLines() As String()
        Return New String() {
            "ui_title|FileDO - конструктор команд",
            "ui_lang|Язык:",
            "ui_target|Цель:",
            "ui_operation|Операция:",
            "ui_drive|Диск:",
            "ui_path|Путь:",
            "ui_source|Источник:",
            "ui_list|Файл списка:",
            "ui_folder|Папка:",
            "ui_dest|Назначение:",
            "ui_size|Размер (МБ):",
            "ui_flags|Флаги:",
            "ui_browse|Обзор",
            "ui_copy|Копировать",
            "ui_run|ВЫПОЛНИТЬ",
            "ui_about|О программе",
            "ui_close|Закрыть",
            "ui_send_logs|Отправить логи автору",
            "about_tip|Версия, ссылки и отправка логов автору",
            "about_title|О программе FileDO",
            "about_tagline|Тесты скорости накопителей, выявление поддельной ёмкости, безопасная очистка, заполнение и работа с дубликатами для Windows - консольная программа и этот конструктор команд к ней.",
            "about_build|Сборка GUI:",
            "about_cli|CLI filedo.exe:",
            "about_author|Автор:",
            "about_links|Ссылки:",
            "about_site|Сайт и загрузки",
            "about_source|Исходный код на GitHub",
            "about_issues|Сообщить о проблеме",
            "about_privacy|Приватность: без телеметрии",
            "about_portfolio|Другие программы автора",
            "about_license|Лицензия MIT. Свободно в использовании, исходный код открыт.",
            "about_logs_hint|Что-то работает не так? Отправьте логи - и это можно будет разобрать. Логи собираются в один zip, который вы сначала видите сами, а письмо отправляете тоже сами.",
            "logs_title|FileDO - отправить логи автору",
            "logs_tip|Собрать найденные на этой машине лог-файлы FileDO в один zip и открыть почтовую программу с адресом автора. Ничего не уходит, пока вы сами не отправите письмо.",
            "logs_confirm|FileDO соберёт в один zip лог-файлы и отчёты, которые он записал на этой машине.\n\nЧто войдёт: отладочный лог GUI, история операций, отчёты check, compare и delete, список пропущенных файлов и короткая справка об этой сборке и об этой Windows.\n\nПути внутри логов могут содержать имена ваших папок и вашей учётной записи. Zip остаётся на диске - его можно открыть и убрать всё, что вы не хотите отправлять.\n\nАвтоматически ничего не отправляется: откроется ваша почтовая программа с адресом автора, а файл вы приложите и отправите сами.\n\nСобрать zip сейчас?",
            "logs_none|Лог-файлы FileDO на этой машине не найдены - отправлять пока нечего.\n\nЧтобы получить лог, запустите GUI так: filedo_win.exe -debug\nИли выполните команду, которая пишет отчёт - check, compare или правило удаления.",
            "logs_ready|Zip готов:\n{0}\n\nСобрано файлов: {1}. Папка открыта, файл в ней выделен, полный путь скопирован в буфер обмена.\n\nПоследний шаг: приложите этот файл к открывшемуся письму и отправьте его.",
            "logs_partial|Часть шагов не выполнилась:",
            "logs_error|Не удалось собрать архив логов:\n{0}",
            "hl_example|Пример:",
            "hl_note|Внимание:",
            "hl_flags|Активные флаги:",
            "dup_title|Опции дубликатов",
            "dup_old|Оставить новейший (old)",
            "dup_new|Оставить старейший (new)",
            "dup_abc|Оставить последний по алфавиту (abc)",
            "dup_xyz|Оставить первый по алфавиту (xyz)",
            "dup_move|Переместить дубликаты в:",
            "cmp_label|Правило удаления:",
            "hl_rule|Правило:",
            "cmprule_none|Только показать различия; ничего не удалять.",
            "cmprule_source|Удалить файлы в Источнике, которые есть и в Назначении.",
            "cmprule_target|Удалить файлы в Назначении, которые есть и в Источнике.",
            "cmprule_old|Удалить более старый файл каждой пары (одинаковое время: пропуск).",
            "cmprule_new|Удалить более новый файл каждой пары (одинаковое время: пропуск).",
            "cmprule_small|Удалить меньший файл каждой пары (одинаковый размер: пропуск).",
            "cmprule_big|Удалить больший файл каждой пары (одинаковый размер: пропуск).",
            "cmprule_old_target|Удалить более старый файл пары, но только если он в Назначении.",
            "cmprule_new_source|Удалить более новый файл пары, но только если он в Источнике.",
            "cmprule_small_source|Удалить меньший файл пары, но только если он в Источнике.",
            "cmprule_big_target|Удалить больший файл пары, но только если он в Назначении.",
            "cdrule_old|Оставить новейшую копию; старые дубликаты удалить или переместить.",
            "cdrule_new|Оставить старейшую копию; новые дубликаты удалить или переместить.",
            "cdrule_abc|Оставить последнее имя по алфавиту; остальные дубликаты убрать.",
            "cdrule_xyz|Оставить первое имя по алфавиту; остальные дубликаты убрать.",
            "op_info|Показать сведения о цели (размер, свободно, файловая система). Только чтение, ничего не меняет.",
            "op_speed|Замерить реальную скорость чтения/записи временным файлом, затем удалить его.",
            "op_test|Выявление поддельной ёмкости: пишет ~100 проверочных файлов (~1% каждый), проверяет их и сообщает, настоящий ли накопитель. 'del' - авто-очистка.",
            "op_fill|Заполнить свободное место тестовыми файлами до отказа. С 'del' затем стирает их - безопасная очистка свободного места.",
            "op_clean|Удалить тестовые файлы FileDO (FILL_*, speedtest_*), оставшиеся на цели.",
            "op_cd|Найти дубликаты по MD5 и применить правило (оставить старейший/новейший/по алфавиту; удалить или переместить).",
            "op_copy|Копировать источник в назначение с авто-стратегией, прогрессом и защитой по тайм-ауту.",
            "op_fastcopy|Высокоскоростное параллельное копирование больших объёмов.",
            "op_synccopy|Однопоточное синхронное копирование (меньше кеширования) - для замера реального ввода-вывода.",
            "op_balanced|Сбалансированное копирование под HDD-HDD (4 потока, буферы 64 МБ).",
            "op_maxcopy|Максимальная производительность (16 потоков, буферы 128 МБ).",
            "op_smartcopy|Проанализировать диски и выбрать лучшую стратегию автоматически.",
            "op_safecopy|Сверхбезопасное копирование для повреждённых дисков: пропускает нечитаемые файлы и логирует их.",
            "op_wipe|Быстро удалить содержимое папки (удалить и создать заново). Сначала просит ввести WIPE.",
            "op_compare|Сравнить два дерева папок и показать различия; необязательное правило удаляет совпавшие файлы.",
            "op_check|Прочитать каждый файл, чтобы найти нечитаемые или медленные; помечает повреждённые.",
            "op_probe|Быстрая проверка ёмкости сырым вводом-выводом. Требует прав администратора, ~1 мин.",
            "op_recover|Восстановить диск после probe (chkdsk + опционально быстрое форматирование).",
            "op_from|Выполнить пакет команд filedo из файла списка (по одной в строке).",
            "op_hist|Показать недавнюю историю операций.",
            "op_help|Показать полную справку командной строки.",
            "fl_max|max: использовать максимальный размер (10 ГБ для speed; fill - до заполнения).",
            "fl_del|del: удалить тестовые файлы автоматически после запуска.",
            "fl_nodel|nodel: оставить тестовый файл, не удалять.",
            "fl_short|short: только краткий вывод.",
            "fl_hist|hist: записать запуск в history.json.",
            "fl_force|--force: пропустить подтверждение WIPE (только обычные цели).",
            "ex_device|Пример: выберите диск - C:  D:  E:",
            "ex_folder|Пример: C:\Temp   D:\Data",
            "ex_network|Пример: \\server\share",
            "ex_file|Пример: C:\data\archive.zip",
            "note_sysdrive|C: - системный диск. Пишущие тесты (test/fill/speed) перенаправляются в %TEMP%\FileDO_Operations (запасной C:\TEMP) и просят подтверждение - это защищает Windows."
        }
    End Function

    Private Function UkLines() As String()
        Return New String() {
            "ui_title|FileDO - конструктор команд",
            "ui_lang|Мова:",
            "ui_target|Ціль:",
            "ui_operation|Операція:",
            "ui_drive|Диск:",
            "ui_path|Шлях:",
            "ui_source|Джерело:",
            "ui_list|Файл списку:",
            "ui_folder|Тека:",
            "ui_dest|Призначення:",
            "ui_size|Розмір (МБ):",
            "ui_flags|Прапорці:",
            "ui_browse|Огляд",
            "ui_copy|Копіювати",
            "ui_run|ВИКОНАТИ",
            "ui_about|Про програму",
            "ui_close|Закрити",
            "ui_send_logs|Надіслати логи автору",
            "about_tip|Версія, посилання та надсилання логів автору",
            "about_title|Про програму FileDO",
            "about_tagline|Тести швидкості носіїв, виявлення підробленої ємності, безпечне очищення, заповнення та робота з дублікатами для Windows - консольна програма і цей конструктор команд до неї.",
            "about_build|Збірка GUI:",
            "about_cli|CLI filedo.exe:",
            "about_author|Автор:",
            "about_links|Посилання:",
            "about_site|Сайт і завантаження",
            "about_source|Вихідний код на GitHub",
            "about_issues|Повідомити про проблему",
            "about_privacy|Приватність: без телеметрії",
            "about_portfolio|Інші програми автора",
            "about_license|Ліцензія MIT. Вільна у використанні, вихідний код відкритий.",
            "about_logs_hint|Щось працює не так? Надішліть логи - і це можна буде розібрати. Логи збираються в один zip, який ви спершу бачите самі, а лист надсилаєте теж самі.",
            "logs_title|FileDO - надіслати логи автору",
            "logs_tip|Зібрати знайдені на цій машині лог-файли FileDO в один zip і відкрити поштову програму з адресою автора. Нічого не надсилається, поки ви самі не надішлете лист.",
            "logs_confirm|FileDO збере в один zip лог-файли та звіти, які він записав на цій машині.\n\nЩо увійде: зневаджувальний лог GUI, історія операцій, звіти check, compare і delete, список пропущених файлів та коротка довідка про цю збірку і про цю Windows.\n\nШляхи всередині логів можуть містити назви ваших тек і вашого облікового запису. Zip залишається на диску - його можна відкрити і прибрати все, що ви не хочете надсилати.\n\nАвтоматично нічого не надсилається: відкриється ваша поштова програма з адресою автора, а файл ви прикладете і надішлете самі.\n\nЗібрати zip зараз?",
            "logs_none|Лог-файлів FileDO на цій машині не знайдено - надсилати поки нічого.\n\nЩоб отримати лог, запустіть GUI так: filedo_win.exe -debug\nАбо виконайте команду, яка пише звіт - check, compare або правило видалення.",
            "logs_ready|Zip готовий:\n{0}\n\nЗібрано файлів: {1}. Тека відкрита, файл у ній виділено, повний шлях скопійовано в буфер обміну.\n\nОстанній крок: прикладіть цей файл до листа, що відкрився, і надішліть його.",
            "logs_partial|Частина кроків не виконалася:",
            "logs_error|Не вдалося зібрати архів логів:\n{0}",
            "hl_example|Приклад:",
            "hl_note|Увага:",
            "hl_flags|Активні прапорці:",
            "dup_title|Опції дублікатів",
            "dup_old|Лишити найновіший (old)",
            "dup_new|Лишити найстаріший (new)",
            "dup_abc|Лишити останній за абеткою (abc)",
            "dup_xyz|Лишити перший за абеткою (xyz)",
            "dup_move|Перемістити дублікати в:",
            "cmp_label|Правило видалення:",
            "hl_rule|Правило:",
            "cmprule_none|Лише показати відмінності; нічого не видаляти.",
            "cmprule_source|Видалити файли в Джерелі, які є й у Призначенні.",
            "cmprule_target|Видалити файли в Призначенні, які є й у Джерелі.",
            "cmprule_old|Видалити старіший файл кожної пари (однаковий час: пропуск).",
            "cmprule_new|Видалити новіший файл кожної пари (однаковий час: пропуск).",
            "cmprule_small|Видалити менший файл кожної пари (однаковий розмір: пропуск).",
            "cmprule_big|Видалити більший файл кожної пари (однаковий розмір: пропуск).",
            "cmprule_old_target|Видалити старіший файл пари, але лише якщо він у Призначенні.",
            "cmprule_new_source|Видалити новіший файл пари, але лише якщо він у Джерелі.",
            "cmprule_small_source|Видалити менший файл пари, але лише якщо він у Джерелі.",
            "cmprule_big_target|Видалити більший файл пари, але лише якщо він у Призначенні.",
            "cdrule_old|Лишити найновішу копію; старі дублікати видалити або перемістити.",
            "cdrule_new|Лишити найстарішу копію; нові дублікати видалити або перемістити.",
            "cdrule_abc|Лишити останнє ім'я за абеткою; решту дублікатів прибрати.",
            "cdrule_xyz|Лишити перше ім'я за абеткою; решту дублікатів прибрати.",
            "op_info|Показати відомості про ціль (розмір, вільно, файлова система). Лише читання, нічого не змінює.",
            "op_speed|Заміряти реальну швидкість читання/запису тимчасовим файлом, потім видалити його.",
            "op_test|Виявлення фейкової ємності: пише ~100 перевірочних файлів (~1% кожен), перевіряє їх і повідомляє, чи диск справжній. 'del' - авто-очищення.",
            "op_fill|Заповнити вільне місце тестовими файлами до краю. З 'del' потім стирає їх - безпечне очищення вільного місця.",
            "op_clean|Видалити тестові файли FileDO (FILL_*, speedtest_*), що лишилися на цілі.",
            "op_cd|Знайти дублікати за MD5 і застосувати правило (лишити найстаріший/найновіший/за абеткою; видалити або перемістити).",
            "op_copy|Копіювати джерело в призначення з авто-стратегією, прогресом і захистом за таймаутом.",
            "op_fastcopy|Високошвидкісне паралельне копіювання великих обсягів.",
            "op_synccopy|Однопотокове синхронне копіювання (менше кешування) - для заміру реального вводу-виводу.",
            "op_balanced|Збалансоване копіювання під HDD-HDD (4 потоки, буфери 64 МБ).",
            "op_maxcopy|Максимальна продуктивність (16 потоків, буфери 128 МБ).",
            "op_smartcopy|Проаналізувати диски та обрати найкращу стратегію автоматично.",
            "op_safecopy|Надбезпечне копіювання для пошкоджених дисків: пропускає нечитані файли та логує їх.",
            "op_wipe|Швидко видалити вміст теки (видалити та створити заново). Спершу просить увести WIPE.",
            "op_compare|Порівняти два дерева тек і показати відмінності; необов'язкове правило видаляє збіги.",
            "op_check|Прочитати кожен файл, щоб знайти нечитані або повільні; позначає пошкоджені.",
            "op_probe|Швидка перевірка ємності сирим вводом-виводом. Потребує прав адміністратора, ~1 хв.",
            "op_recover|Відновити диск після probe (chkdsk + опційно швидке форматування).",
            "op_from|Виконати пакет команд filedo з файлу списку (по одній у рядку).",
            "op_hist|Показати недавню історію операцій.",
            "op_help|Показати повну довідку командного рядка.",
            "fl_max|max: використати максимальний розмір (10 ГБ для speed; fill - до заповнення).",
            "fl_del|del: видалити тестові файли автоматично після запуску.",
            "fl_nodel|nodel: лишити тестовий файл, не видаляти.",
            "fl_short|short: лише короткий вивід.",
            "fl_hist|hist: записати запуск у history.json.",
            "fl_force|--force: пропустити підтвердження WIPE (лише звичайні цілі).",
            "ex_device|Приклад: оберіть диск - C:  D:  E:",
            "ex_folder|Приклад: C:\Temp   D:\Data",
            "ex_network|Приклад: \\server\share",
            "ex_file|Приклад: C:\data\archive.zip",
            "note_sysdrive|C: - системний диск. Пишучі тести (test/fill/speed) перенаправляються в %TEMP%\FileDO_Operations (запасний C:\TEMP) і просять підтвердження - це захищає Windows."
        }
    End Function

    Private Function DeLines() As String()
        Return New String() {
            "ui_title|FileDO - Befehlsbaukasten",
            "ui_lang|Sprache:",
            "ui_target|Ziel:",
            "ui_operation|Operation:",
            "ui_drive|Laufwerk:",
            "ui_path|Pfad:",
            "ui_source|Quelle:",
            "ui_list|Listendatei:",
            "ui_folder|Ordner:",
            "ui_dest|Ziel (Kopie):",
            "ui_size|Größe (MB):",
            "ui_flags|Flags:",
            "ui_browse|Durchsuchen",
            "ui_copy|Befehl kopieren",
            "ui_run|AUSFÜHREN",
            "ui_about|Über das Programm",
            "ui_close|Schließen",
            "ui_send_logs|Logs an den Autor senden",
            "about_tip|Version, Links und das Senden der Logs an den Autor",
            "about_title|Über FileDO",
            "about_tagline|Geschwindigkeitstests für Datenträger, Erkennung vorgetäuschter Kapazität, sicheres Löschen, Füllen und Umgang mit Duplikaten für Windows - ein Kommandozeilenprogramm und dieser Befehlsbaukasten dafür.",
            "about_build|GUI-Build:",
            "about_cli|CLI filedo.exe:",
            "about_author|Autor:",
            "about_links|Links:",
            "about_site|Website und Downloads",
            "about_source|Quellcode auf GitHub",
            "about_issues|Ein Problem melden",
            "about_privacy|Datenschutz: keine Telemetrie",
            "about_portfolio|Weitere Programme des Autors",
            "about_license|MIT-Lizenz. Frei nutzbar, der vollständige Quellcode ist offen.",
            "about_logs_hint|Etwas verhält sich falsch? Senden Sie die Logs, dann kann man es sich ansehen. Die Logs kommen in ein Zip, das Sie zuerst selbst sehen, und die Mail senden Sie ebenfalls selbst.",
            "logs_title|FileDO - Logs an den Autor senden",
            "logs_tip|Die auf diesem Rechner gefundenen FileDO-Logdateien in ein Zip packen und das Mailprogramm mit der Adresse des Autors öffnen. Es wird nichts gesendet, bevor Sie die Mail selbst abschicken.",
            "logs_confirm|FileDO sammelt die Log- und Berichtsdateien, die es auf diesem Rechner geschrieben hat, in einem Zip.\n\nEnthalten sind: das Debug-Log der GUI, der Verlauf der Operationen, die Berichte von check, compare und delete, die Skip-Liste und eine kurze Übersicht zu diesem Build und zu diesem Windows.\n\nPfade in diesen Logs können Ihre Ordner- und Kontonamen enthalten. Das Zip bleibt auf Ihrer Festplatte - Sie können es öffnen und alles entfernen, was Sie nicht teilen möchten.\n\nEs wird nichts automatisch gesendet: Ihr Mailprogramm öffnet sich mit der Adresse des Autors, die Datei hängen Sie selbst an und senden selbst.\n\nZip jetzt erstellen?",
            "logs_none|Auf diesem Rechner wurden keine FileDO-Logdateien gefunden, es gibt also noch nichts zu senden.\n\nFür ein Log starten Sie die GUI so: filedo_win.exe -debug\nOder führen Sie einen Befehl aus, der einen Bericht schreibt - check, compare oder eine Löschregel.",
            "logs_ready|Das Zip ist fertig:\n{0}\n\nGesammelte Dateien: {1}. Der Ordner ist geöffnet, die Datei darin markiert, und der vollständige Pfad liegt in der Zwischenablage.\n\nLetzter Schritt: Hängen Sie diese Datei an die gerade geöffnete Mail an und senden Sie sie.",
            "logs_partial|Einige Schritte sind fehlgeschlagen:",
            "logs_error|Das Log-Archiv konnte nicht erstellt werden:\n{0}",
            "hl_example|Beispiel:",
            "hl_note|Hinweis:",
            "hl_flags|Aktive Flags:",
            "dup_title|Duplikat-Optionen",
            "dup_old|Neuestes behalten (old)",
            "dup_new|Ältestes behalten (new)",
            "dup_abc|Letztes alphabetisch behalten (abc)",
            "dup_xyz|Erstes alphabetisch behalten (xyz)",
            "dup_move|Duplikate verschieben nach:",
            "cmp_label|Löschregel:",
            "hl_rule|Regel:",
            "cmprule_none|Nur Unterschiede melden; nichts löschen.",
            "cmprule_source|Dateien in der Quelle löschen, die auch im Ziel existieren.",
            "cmprule_target|Dateien im Ziel löschen, die auch in der Quelle existieren.",
            "cmprule_old|Die ältere Datei jedes Paares löschen (gleiche Zeit: überspringen).",
            "cmprule_new|Die neuere Datei jedes Paares löschen (gleiche Zeit: überspringen).",
            "cmprule_small|Die kleinere Datei jedes Paares löschen (gleiche Größe: überspringen).",
            "cmprule_big|Die größere Datei jedes Paares löschen (gleiche Größe: überspringen).",
            "cmprule_old_target|Die ältere Datei jedes Paares löschen, aber nur wenn diese Seite das Ziel ist.",
            "cmprule_new_source|Die neuere Datei jedes Paares löschen, aber nur wenn diese Seite die Quelle ist.",
            "cmprule_small_source|Die kleinere Datei jedes Paares löschen, aber nur wenn diese Seite die Quelle ist.",
            "cmprule_big_target|Die größere Datei jedes Paares löschen, aber nur wenn diese Seite das Ziel ist.",
            "cdrule_old|Die neueste Kopie behalten; ältere Duplikate löschen oder verschieben.",
            "cdrule_new|Die älteste Kopie behalten; neuere Duplikate löschen oder verschieben.",
            "cdrule_abc|Den alphabetisch letzten Namen behalten; übrige Duplikate entfernen.",
            "cdrule_xyz|Den alphabetisch ersten Namen behalten; übrige Duplikate entfernen.",
            "op_info|Zieldetails anzeigen (Größe, frei, Dateisystem). Nur Lesen, ändert nichts.",
            "op_speed|Echte Lese-/Schreibgeschwindigkeit mit einer temporären Datei messen, dann löschen.",
            "op_test|Gefälschte Kapazität erkennen: schreibt ~100 Prüfdateien (~1% je), prüft sie und meldet, ob das Gerät echt ist. 'del' räumt automatisch auf.",
            "op_fill|Freien Speicher mit Testdateien bis voll füllen. Mit 'del' danach löschen - sicheres Löschen des freien Speichers.",
            "op_clean|FileDO-Testdateien (FILL_*, speedtest_*) am Ziel löschen.",
            "op_cd|Duplikate per MD5 finden und Regel anwenden (ältestes/neuestes/alphabetisch behalten; löschen oder verschieben).",
            "op_copy|Quelle nach Ziel kopieren mit Auto-Strategie, Fortschritt und Timeout-Schutz.",
            "op_fastcopy|Schnelles paralleles Kopieren großer Datenmengen.",
            "op_synccopy|Einzel-Thread synchrones Kopieren (weniger Caching) - zum Messen echter E/A.",
            "op_balanced|Ausgewogenes Kopieren für HDD-zu-HDD (4 Threads, 64-MB-Puffer).",
            "op_maxcopy|Maximale Leistung (16 Threads, 128-MB-Puffer).",
            "op_smartcopy|Laufwerke analysieren und beste Strategie automatisch wählen.",
            "op_safecopy|Ultrasicheres Kopieren für beschädigte Laufwerke: überspringt unlesbare Dateien und protokolliert sie.",
            "op_wipe|Ordnerinhalt schnell löschen (löschen & neu erstellen). Fragt zuerst nach WIPE.",
            "op_compare|Zwei Ordnerbäume vergleichen und Unterschiede melden; eine optionale Regel löscht passende Dateien.",
            "op_check|Jede Datei lesen, um unlesbare oder langsame zu finden; markiert beschädigte.",
            "op_probe|Schnelle Roh-E/A-Kapazitätsprüfung. Erfordert Administrator, ~1 Min.",
            "op_recover|Laufwerk nach probe wiederherstellen (chkdsk + optional Schnellformatierung).",
            "op_from|Eine Reihe von filedo-Befehlen aus einer Listendatei ausführen (einer pro Zeile).",
            "op_hist|Den letzten Verlauf anzeigen.",
            "op_help|Die vollständige Kommandozeilenhilfe anzeigen.",
            "fl_max|max: maximale Größe verwenden (10 GB bei speed; fill bis voll).",
            "fl_del|del: Testdateien nach dem Lauf automatisch löschen.",
            "fl_nodel|nodel: Testdatei behalten statt löschen.",
            "fl_short|short: nur kurze Ausgabe.",
            "fl_hist|hist: diesen Lauf in history.json protokollieren.",
            "fl_force|--force: WIPE-Bestätigung überspringen (nur normale Ziele).",
            "ex_device|Beispiel: Laufwerk wählen - C:  D:  E:",
            "ex_folder|Beispiel: C:\Temp   D:\Data",
            "ex_network|Beispiel: \\server\share",
            "ex_file|Beispiel: C:\data\archive.zip",
            "note_sysdrive|C: ist das Systemlaufwerk. Schreibtests (test/fill/speed) werden nach %TEMP%\FileDO_Operations (Ersatz C:\TEMP) umgeleitet und fragen nach - das schützt Windows."
        }
    End Function

    Private Function FrLines() As String()
        Return New String() {
            "ui_title|FileDO - constructeur de commandes",
            "ui_lang|Langue :",
            "ui_target|Cible :",
            "ui_operation|Opération :",
            "ui_drive|Disque :",
            "ui_path|Chemin :",
            "ui_source|Source :",
            "ui_list|Fichier liste :",
            "ui_folder|Dossier :",
            "ui_dest|Destination :",
            "ui_size|Taille (Mo) :",
            "ui_flags|Options :",
            "ui_browse|Parcourir",
            "ui_copy|Copier la commande",
            "ui_run|EXÉCUTER",
            "ui_about|À propos",
            "ui_close|Fermer",
            "ui_send_logs|Envoyer les logs à l'auteur",
            "about_tip|Version, liens et envoi des logs à l'auteur",
            "about_title|À propos de FileDO",
            "about_tagline|Tests de vitesse des supports, détection de capacité falsifiée, effacement sécurisé, remplissage et gestion des doublons pour Windows - un outil en ligne de commande et ce constructeur de commandes.",
            "about_build|Version de l'interface:",
            "about_cli|CLI filedo.exe:",
            "about_author|Auteur:",
            "about_links|Liens:",
            "about_site|Site et téléchargements",
            "about_source|Code source sur GitHub",
            "about_issues|Signaler un problème",
            "about_privacy|Confidentialité: aucune télémétrie",
            "about_portfolio|Autres outils de l'auteur",
            "about_license|Licence MIT. Libre d'utilisation, et tout le code source est ouvert.",
            "about_logs_hint|Quelque chose ne fonctionne pas bien? Envoyez les logs et cela pourra être examiné. Les logs sont regroupés dans un zip que vous voyez d'abord, et c'est vous qui envoyez le message.",
            "logs_title|FileDO - envoyer les logs à l'auteur",
            "logs_tip|Regrouper dans un zip les fichiers de log FileDO trouvés sur cette machine, puis ouvrir votre programme de messagerie avec l'adresse de l'auteur. Rien n'est envoyé avant que vous envoyiez le message vous-même.",
            "logs_confirm|FileDO va regrouper dans un seul zip les fichiers de log et les rapports qu'il a écrits sur cette machine.\n\nContenu: le log de débogage de l'interface, l'historique des opérations, les rapports check, compare et delete, la liste des fichiers ignorés, et un court résumé de cette version et de ce Windows.\n\nLes chemins présents dans ces logs peuvent contenir les noms de vos dossiers et de votre compte. Le zip reste sur votre disque: vous pouvez l'ouvrir et retirer tout ce que vous ne voulez pas partager.\n\nRien n'est envoyé automatiquement: votre programme de messagerie s'ouvre avec l'adresse de l'auteur, c'est vous qui joignez le fichier et qui envoyez.\n\nCréer le zip maintenant?",
            "logs_none|Aucun fichier de log FileDO n'a été trouvé sur cette machine, il n'y a donc rien à envoyer pour l'instant.\n\nPour produire un log, lancez l'interface ainsi: filedo_win.exe -debug\nOu exécutez une commande qui écrit un rapport - check, compare ou une règle de suppression.",
            "logs_ready|Le zip est prêt:\n{0}\n\nFichiers collectés: {1}. Le dossier est ouvert avec le fichier sélectionné, et le chemin complet est dans le presse-papiers.\n\nDernière étape: joignez ce fichier au message qui vient de s'ouvrir et envoyez-le.",
            "logs_partial|Certaines étapes ont échoué:",
            "logs_error|Impossible de créer l'archive des logs:\n{0}",
            "hl_example|Exemple :",
            "hl_note|Remarque :",
            "hl_flags|Options actives :",
            "dup_title|Options des doublons",
            "dup_old|Garder le plus récent (old)",
            "dup_new|Garder le plus ancien (new)",
            "dup_abc|Garder le dernier alpha (abc)",
            "dup_xyz|Garder le premier alpha (xyz)",
            "dup_move|Déplacer les doublons vers :",
            "cmp_label|Règle de suppression :",
            "hl_rule|Règle :",
            "cmprule_none|Signaler seulement les différences ; ne rien supprimer.",
            "cmprule_source|Supprimer les fichiers de la Source présents aussi dans la Destination.",
            "cmprule_target|Supprimer les fichiers de la Destination présents aussi dans la Source.",
            "cmprule_old|Supprimer le fichier le plus ancien de chaque paire (temps égal : ignorer).",
            "cmprule_new|Supprimer le fichier le plus récent de chaque paire (temps égal : ignorer).",
            "cmprule_small|Supprimer le fichier le plus petit de chaque paire (taille égale : ignorer).",
            "cmprule_big|Supprimer le fichier le plus gros de chaque paire (taille égale : ignorer).",
            "cmprule_old_target|Supprimer le fichier le plus ancien de chaque paire, mais seulement si ce côté est la Destination.",
            "cmprule_new_source|Supprimer le fichier le plus récent de chaque paire, mais seulement si ce côté est la Source.",
            "cmprule_small_source|Supprimer le fichier le plus petit de chaque paire, mais seulement si ce côté est la Source.",
            "cmprule_big_target|Supprimer le fichier le plus gros de chaque paire, mais seulement si ce côté est la Destination.",
            "cdrule_old|Garder la copie la plus récente ; supprimer ou déplacer les doublons plus anciens.",
            "cdrule_new|Garder la copie la plus ancienne ; supprimer ou déplacer les doublons plus récents.",
            "cdrule_abc|Garder le dernier nom alphabétique ; retirer les autres doublons.",
            "cdrule_xyz|Garder le premier nom alphabétique ; retirer les autres doublons.",
            "op_info|Afficher les détails de la cible (taille, libre, système de fichiers). Lecture seule, ne change rien.",
            "op_speed|Mesurer la vitesse réelle de lecture/écriture avec un fichier temporaire, puis le supprimer.",
            "op_test|Détecter une fausse capacité : écrit ~100 fichiers de vérification (~1% chacun), les contrôle et indique si l'appareil est authentique. 'del' nettoie automatiquement.",
            "op_fill|Remplir l'espace libre de fichiers de test jusqu'au bout. Avec 'del', les efface ensuite - effacement sécurisé de l'espace libre.",
            "op_clean|Supprimer les fichiers de test FileDO (FILL_*, speedtest_*) restés sur la cible.",
            "op_cd|Trouver les doublons par MD5 et appliquer la règle (garder le plus ancien/récent/alphabétique ; supprimer ou déplacer).",
            "op_copy|Copier la source vers la destination avec stratégie auto, progression et protection par délai.",
            "op_fastcopy|Copie parallèle à haute vitesse pour de gros volumes.",
            "op_synccopy|Copie synchronisée mono-thread (moins de cache) - pour mesurer les E/S réelles.",
            "op_balanced|Copie équilibrée pour HDD-vers-HDD (4 threads, tampons de 64 Mo).",
            "op_maxcopy|Performance maximale (16 threads, tampons de 128 Mo).",
            "op_smartcopy|Analyser les disques et choisir la meilleure stratégie automatiquement.",
            "op_safecopy|Copie ultra-sûre pour disques endommagés : ignore les fichiers illisibles et les journalise.",
            "op_wipe|Effacer rapidement le contenu du dossier (supprimer & recréer). Demande d'abord de taper WIPE.",
            "op_compare|Comparer deux arborescences et signaler les différences ; une règle facultative supprime les fichiers correspondants.",
            "op_check|Lire chaque fichier pour repérer les illisibles ou lents ; marque les fichiers endommagés.",
            "op_probe|Sonde de capacité E/S brute rapide. Nécessite l'administrateur, ~1 min.",
            "op_recover|Récupérer un disque après probe (chkdsk + formatage rapide optionnel).",
            "op_from|Exécuter un lot de commandes filedo depuis un fichier liste (une par ligne).",
            "op_hist|Afficher l'historique récent des opérations.",
            "op_help|Afficher l'aide complète en ligne de commande.",
            "fl_max|max : utiliser la taille maximale (10 Go pour speed ; fill jusqu'au plein).",
            "fl_del|del : supprimer les fichiers de test automatiquement après l'exécution.",
            "fl_nodel|nodel : garder le fichier de test au lieu de le supprimer.",
            "fl_short|short : sortie brève uniquement.",
            "fl_hist|hist : journaliser cette exécution dans history.json.",
            "fl_force|--force : ignorer la confirmation WIPE (cibles normales uniquement).",
            "ex_device|Exemple : choisissez un disque - C:  D:  E:",
            "ex_folder|Exemple : C:\Temp   D:\Data",
            "ex_network|Exemple : \\server\share",
            "ex_file|Exemple : C:\data\archive.zip",
            "note_sysdrive|C: est le disque système. Les tests d'écriture (test/fill/speed) sont redirigés vers %TEMP%\FileDO_Operations (repli C:\TEMP) et demandent confirmation - cela protège Windows."
        }
    End Function

End Module
